### ISSUE TITLE
Removing auto-generated 'Device' tab

### ISSUE THREAD

**Issue by jeanlaurent** [bugsnag/bugsnag-dotnet#52]
I'm trying to get rid of the 'Device' tab in the metadata.

I'm trying this, with no luck :

```
bugsnag.Config.BeforeNotify(error =>
{
  error.Metadata.RemoveTab("DEVICE");
  return true;
});
```

How can I get rid of this tab ?

**Comment by kattrali** [comment]
Hi @jeanlaurent, I believe the tab name is actually lowercase in the payload. Did you try `error.Metadata.RemoveTab("device")`?

**Comment by kattrali** [comment]
Closing due to inactivity, `device` should fix the problem.

**Comment by VishalDPrajapati** [comment]
The problems still persists...I  cannot remove "Device" Tab using error.Metadata.RemoveTab("device")

**Comment by CodeHex** [comment]
The `error.Metadata.RemoveTab()` call won't work for device information as this isn't stored as metadata but captured and appended to the notification before being sent (see https://github.com/bugsnag/bugsnag-dotnet/blob/v1.4/src/Bugsnag/NotificationFactory.cs#L79)

Reopening this issue for further investigation. Note that this only applies to v1.4.

**Comment by snmaynard** [comment]
Yeah this is fixed in v2 looking at https://docs.bugsnag.com/platforms/dotnet/asp-net-core/automatically-captured-data/#device-information

**Comment by snmaynard** [comment]
Closing this as in the new version of the notifier this is possible to do in a callback, as linked to above.
